import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./sidebar/page";
import Header from "./header/page";
import Footer from "./footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <Header />
        </div>

        <div className={`flex `}>
          <div>
            <Sidebar />
          </div>
          <div>{children}</div>
        </div>

        {/* Temp */}

        {/* <div>
          <Footer />
        </div> */}
      </body>
    </html>
  );
}
